# Generated by Django 3.2.3 on 2021-06-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedata',
            name='pattern',
            field=models.IntegerField(default=0),
        ),
    ]
