# Generated by Django 3.2.3 on 2021-06-09 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_facedata_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
