# Generated by Django 3.2.3 on 2021-06-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_facedata_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedata',
            name='confidence',
            field=models.IntegerField(default=80),
        ),
    ]
